### ISSUE TITLE
installation of plugin cause issue on analysis

### ISSUE THREAD

**Issue by SSANSH** [insideapp-oss/sonar-apple#58] opened 2022-12-23 11:36 UTC
### Issue Description
I Install the latest "0.2.0" version of the plugin on my sonar and restart then.
I can saw plugin install on list of plugin (admin section).
however the plugin break all pipeline even if language is not "Swift and Objective-C".

##### Complete output when running sonar-scanner, including the stack trace and command used
<details>
  <pre>
ERROR: Error during SonarScanner execution
org.picocontainer.PicoCompositionException: Either the specified parameters do not match any of the following constructors: [fr.insideapp.sonarqube.objc.issues.oclint.OCLintSensor(org.sonar.api.config.Configuration,org.sonar.api.batch.fs.FileSystem,fr.insideapp.sonarqube.objc.issues.oclint.interfaces.OCLintJSONDatabaseBuildable,fr.insideapp.sonarqube.objc.issues.oclint.interfaces.OCLintExtractable,fr.insideapp.sonarqube.objc.issues.oclint.interfaces.OCLintReportParsable,fr.insideapp.sonarqube.apple.commons.issues.ReportIssueRecorder)]; OR the constructors were not accessible for 'fr.insideapp.sonarqube.objc.issues.oclint.OCLintSensor'
	at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:200)
	at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:110)
	at org.picocontainer.injectors.ConstructorInjector.access$100(ConstructorInjector.java:51)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:331)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:606)
	at org.picocontainer.DefaultPicoContainer.getComponents(DefaultPicoContainer.java:587)
	at org.sonar.core.platform.ComponentContainer.getComponentsByType(ComponentContainer.java:291)
	at org.sonar.scanner.bootstrap.AbstractExtensionDictionnary.completeScannerExtensions(AbstractExtensionDictionnary.java:82)
	at org.sonar.scanner.bootstrap.AbstractExtensionDictionnary.getExtensions(AbstractExtensionDictionnary.java:77)
	at org.sonar.scanner.bootstrap.AbstractExtensionDictionnary.getFilteredExtensions(AbstractExtensionDictionnary.java:67)
	at org.sonar.scanner.sensor.ModuleSensorExtensionDictionnary.selectSensors(ModuleSensorExtensionDictionnary.java:40)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$0(ModuleSensorsExecutor.java:52)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:52)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)

</pre>
</details>

### Environment

<details>
  <pre>Community EditionVersion 8.9.10 (build 61524)</pre>
</details>

**Comment by gaelfoppolo** [comment] 2022-12-23 16:49
Hi @SSANSH, thank you for reporting the issue and sorry for the inconvenience.
After some tests on my end, I was able to determine that is related to the SonarQube version you use, the 8.9.10.
When using this version, I also reproduce the crash.
However, when using a newer version, the crash disappears.

Can you try with the 9.4.0 and tell me if this is happening? This is the version I use.
In the meantime I will investigate the crash.

**Comment by gaelfoppolo** [comment] 2022-12-23 17:13
I opened #59 with a fix to the issue.

**Comment by SSANSH** [comment] 2023-01-04 15:41
Unfortunately I cannot test on version 9.4.0 because 9.4.0 is not yet an LTS.
Thats why I test on 8.9.10
I saw that you provide a fix, do you have a new version with this fix (> 0.2.0).

**Comment by gaelfoppolo** [comment] 2023-01-04 16:31
I issued a fix release, [0.2.1](https://github.com/insideapp-oss/sonar-apple/releases/tag/0.2.1).
Closing since this is solved.

**Closed by gaelfoppolo** 2023-01-04 16:31 UTC
Labels: bug

**Comment by SSANSH** [comment] 2023-01-04 17:48
@gaelfoppolo ok I will reinstall then tomorow and comeback to you in case of issue, thanks for the version.

**Comment by SSANSH** [comment] 2023-01-05 08:31
@gaelfoppolo looks good, thanks for your support.
